### ISSUE TITLE
Extremely nitty feedback

### ISSUE THREAD

**Issue by mgyucht** [jdsalaro/jdsalaro.com#1]
Loved your overview of `asdf`! Just wanted to let you know that Sisyphus is misspelled in the second paragraph of "Historical Detour: Using Sand Castles to Create “Dependable” Software" and that kind of thing keeps me up at night, so I thought I would let you know.

**Comment by jdsalaro** [comment]
@mgyucht, and what a typo that was!
Thank you for reaching out and letting me know; I appreciate it.
It's fixed ( including the SVGs ) !
