### ISSUE TITLE
Great artcile!

### ISSUE THREAD

**Issue by yaakumahcrystal** [jdsalaro/jdsalaro.com#1]
Just wanted to write to let you know your article "A Quick Look into Microsoft’s New Default Font" was the best and most comprehensive description of the upcoming font changes I read, whereas all other articles are very high level. Very well written and great use of images. Thank you!

I'll add that what I haven't seen in the different overviews I've read (perhaps it is not relevant because it is the same) is whether Aptos will use up more or less ink when printing. I know there are some printer friendly fonts and was wondering if that was a consideration between calibri and aptos. I assume that since aptos is heavier it will use up more ink

**Comment by jdsalaro** [comment]
Thanks for the kind feedback @yaakumahcrystal !

> whether Aptos will use up more or less ink when printing

That's a good point, and one worth looking a bit more into. I've added it to my Addendum Nodes on the post for the future. 

Having said that, I'm not sure when you last had a look at the post, but I've added a Lorem-Ipsum comparison with actual paragraphs which convey better how the typefaces might look on print, [this is the section](https://jdsalaro.com/note/comparison-new-microsoft-default-font-calibri-aptos/#lorem-ipsum). You may find that interesting.

Cheers !

**Comment by yaakumahcrystal** [comment]
Love the Lorem-Ipsum comparison... and again I admire your thoroughness in
helping readers understand the differences 😊.

Based on Aptos screenshot and left and Calibri light on the right, it
certainly would suggest we'll be using more ink unfortunately. But as you
mentioned we should be able to reset our defaults. It's a shame the Aptos
default though will require more ink since I suspect most folks won't set
their defaults. Just seems less environmentally friendly. I will not go
into any conspiracy theories about Microsoft now being in cahoots with big
ink lol
[image: image.png]
